plugins {
    id 'com.android.application'
}
android {
    namespace 'com.example.usbbarcodescanner'
    compileSdk 34
    defaultConfig {
        applicationId "com.example.usbbarcodescanner"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
    implementation 'com.google.mlkit:barcode-scanning:17.2.0'
}
