name: Android CI Build APK

on:
  push:
    branches: [ "main" ]  # Tự động build khi push code lên nhánh main
  workflow_dispatch:      # Vẫn giữ nút bấm thủ công nếu muốn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Lay code tu kho chua
      uses: actions/checkout@v4

    - name: 2. Thiet lap moi truong Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Thiet lap bo may Gradle thuc thi
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.7

    - name: 4. Bat dau dong goi APK
      run: gradle assembleDebug --no-daemon

    - name: 5. Xuat file APK ra ngoai de tai ve
      uses: actions/upload-artifact@v4
      with:
        name: Wifi5GForce-APK-Thanh-Cong  # Đổi tên gói xuất ra
        path: app/build/outputs/apk/debug/app-debug.apk
